version: '3.7'

volumes:
    pgdata:
        driver: local

services:
    nginx:
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/configs:/etc/nginx/conf.d:ro
            - ./docker/nginx/ssl:/usr/local/nginx/conf:ro
            - ./panther_documents/static:/srv/www/panther_documents/static
            - ./panther_documents/media:/srv/www/panther_documents/media
        depends_on:
            - python

    python:
        restart: always
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        volumes:
            - ./panther_documents:/srv/www/panther_documents
        expose:
          - 8000
        ports:
            - "8000:8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        env_file: .env
        environment:
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
